In [1]:
## Métodos iterativos para solução de sistemas lineares

In [2]:
import numpy as np

In [35]:
#Vamos resolver o sistema linear Mx = b
# Para isso, declaramos a matriz M e o vetor b
M = np.array([
    [-5.1,2,3],
    [5,8,2],
    [1,0,3],
])
b = np.array([1,2,3])

In [36]:
#Encontramos a resposta explicitamente como referência
np.linalg.solve(M,b)

array([ 0.27842227, -0.15081206,  0.90719258])

In [37]:
#Método de Jacobi
#Extrai a diagonal de uma matriz e pega a sua inversa
D = np.diag(np.diag(M))
D_inversa = np.diag(1/np.diag(M))

In [38]:
#Extraimos a matriz B
R = M - D

print("Matriz resto:")
print(R)

Matriz resto:
[[ 0.  2.  3.]
 [ 5.  0.  2.]
 [ 1.  0.  0.]]


In [45]:
#Escolhemos um chute inicial
x = [1,2,3]

#Iteramos várias vezes
for i in range(200):
    print('iteração', i)
    y = np.dot(D_inversa, (b - np.dot(R,x)))
    delta = np.sum(np.abs(x - y))
    if delta < 1e-3:
        break
    x = y
    print(x)

iteração 0
[ 2.35294118 -1.125       0.66666667]
iteração 1
[-0.24509804 -1.3872549   0.21568627]
iteração 2
[-0.61322568  0.34926471  1.08169935]
iteração 3
[ 0.57718185  0.36284121  1.20440856]
iteração 4
[ 0.65468787 -0.4118408   0.80760605]
iteração 5
[ 0.11747775 -0.36108143  0.78177071]
iteração 6
[ 0.12218613 -0.01886627  0.96084075]
iteração 7
[ 0.36172347 -0.06657652  0.95927129]
iteração 8
[ 0.34209036 -0.21589499  0.87942551]
iteração 9
[ 0.23656599 -0.18366285  0.88596988]
iteração 10
[ 0.25305567 -0.11934621  0.92114467]
iteração 11
[ 0.29896894 -0.13844596  0.91564811]
iteração 12
[ 0.28824557 -0.16576761  0.90034369]
iteração 13
[ 0.2685286  -0.1552394   0.90391814]
iteração 14
[ 0.27475993 -0.14380991  0.91049047]
iteração 15
[ 0.28310815 -0.14934757  0.90841336]
iteração 16
[ 0.27971469 -0.15404594  0.90563062]
iteração 17
[ 0.27623529 -0.15122934  0.90676177]
iteração 18
[ 0.27800522 -0.1493375   0.90792157]
iteração 19
[ 0.27942936 -0.15073366  0.90733159]
iteração 2

In [46]:
def solve(M,b, max_iter=100, tol=1e-5):
    """
    Resolve o sistema linear M x = b, retornando x.
    
    Utiliza o método de Jacobi
    """
    M = np.asarray(M)
    b = np.asarray(b)
    
    #Extrai D Dinv e R
    diagonal_vetor = np.diag(M)
    D = np.diag(diagonal_vetor)
    Dinv = np.diag(1/diagonal_vetor)
    R = M - D
    
    #Realiza o loop inicial
    x = b
    for i in range(max_iter):
        x_ = np.dot(Dinv, (b - np.dot(R,x)))
        if np.sum(np.abs(x - x_)) < tol:
            return x_
        x = x_
    return ValueError('método não convergiu!')

In [47]:
solve(M,b)

array([ 0.27842366, -0.15081033,  0.90719361])